services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

   

  airflow-init:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.1}
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/nyc-de-project00-2929bdfd1a68.json
      - GCP_BUCKET_ID=nyc-de-project00-bucket
      - PROJECT_ID=nyc-de-project00
      - BQ_DATASET_ID=nyc-de-project00.nyc_de_bq00
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./credentials:/opt/airflow/credentials
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 60s
      timeout: 60s
      retries: 5
    

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/nyc-de-project00-2929bdfd1a68.json
      - GCP_BUCKET_ID=nyc-de-project00-bucket
      - PROJECT_ID=nyc-de-project00
      - BQ_DATASET_ID=nyc-de-project00.nyc_de_bq00
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./credentials:/opt/airflow/credentials
    command: scheduler